import type { Metadata } from "next";
import Link from "next/link";
import { PageIntro } from "@/components/marketing/page-intro";

export const metadata: Metadata = { title: "Privacy", description: "How Hajime handles information submitted through this website.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  return <div className="marketing-container marketing-page marketing-page-narrow legal-page"><PageIntro eyebrow="Privacy" title="Your information should have a clear purpose.">This notice describes the information Hajime collects through the public website and how it is used. Effective July 12, 2026.</PageIntro><section><h2>Information we collect</h2><p>When you request discovery, we collect your name, email, country, current business, target timeline, and the situation you choose to describe. We may also receive basic technical information needed to operate and secure the website.</p></section><section><h2>How we use it</h2><p>We use inquiry information to evaluate fit, respond within one business day, prepare for a discovery conversation, and maintain a record of the commercial relationship. We do not ask for identity documents, financial records, or other sensitive formation documents through this form.</p></section><section><h2>Sharing and retention</h2><p>We do not sell inquiry information. Information may be handled by service providers that operate the website and lead system. We share information with professional or operating providers only for an approved engagement purpose. Records are retained only as long as reasonably needed for these purposes, legal obligations, or dispute prevention.</p></section><section><h2>Your choices</h2><p>You may ask to access, correct, or delete inquiry information, subject to applicable obligations. Submit the request through the <Link href="/book-consultation">discovery page</Link> and state that it is a privacy request.</p></section><section><h2>Public-form boundary</h2><p>Do not send identity documents, bank records, signatures, tax records, or formation evidence through the public website. An engagement-specific transfer method is identified before sensitive information is requested.</p></section></div>;
}
