import type { Metadata } from "next";
import Link from "next/link";
import { PageIntro } from "@/components/marketing/page-intro";

export const metadata: Metadata = { title: "About", description: "Why Hajime exists and how independent coordination improves business formation in Japan.", alternates: { canonical: "/about" } };

export default function AboutPage() {
  return <div className="marketing-container marketing-page"><PageIntro eyebrow="About Hajime" title="Built for the space between a decision and a functioning business.">Japan has capable specialists. The harder problem is knowing what comes next, who owns it, and how one decision affects every other workstream.</PageIntro><section className="editorial-grid"><div><span className="marketing-eyebrow">Our role</span><h2>Make the whole journey legible.</h2></div><div className="editorial-copy"><p>Hajime is an independent coordination service for international founders forming and launching businesses in Japan. We translate a complex, multi-provider process into one sequenced plan and keep the handoffs moving.</p><p>We do not replace professional judgment. Licensed providers own regulated legal, tax, accounting, immigration, and filing work. Hajime owns visibility, coordination, and the operating rhythm around that work.</p></div></section><section className="principle-grid"><article><span>Clarity</span><h3>No hidden sequence</h3><p>You should always know the current step, the next step, who is responsible, and the expected timeframe.</p></article><article><span>Independence</span><h3>The outcome comes first</h3><p>Provider recommendations begin with the needs of the launch, not advertising or referral revenue.</p></article><article><span>Restraint</span><h3>Only the work that matters</h3><p>We add coordination where it reduces risk or workload, and leave unnecessary complexity out.</p></article></section><div className="page-cta"><h2>See whether Hajime fits your formation.</h2><Link className="button button-primary button-large" href="/book-consultation">Book a discovery call</Link></div></div>;
}
