import type { Metadata } from "next";
import Link from "next/link";
import { PageIntro } from "@/components/marketing/page-intro";

export const metadata: Metadata = { title: "Terms", description: "Website terms and service boundaries for Hajime Japan.", alternates: { canonical: "/terms" } };

export default function TermsPage() {
  return <div className="marketing-container marketing-page marketing-page-narrow legal-page"><PageIntro eyebrow="Terms" title="Clear boundaries begin before an engagement.">These website terms explain the limited purpose of Hajime&apos;s public information. Effective July 12, 2026.</PageIntro><section><h2>Website information</h2><p>This website provides general information about Hajime&apos;s coordination service. It is not legal, tax, accounting, immigration, financial, insurance, employment, or other regulated professional advice, and it should not be relied on as such.</p></section><section><h2>No professional relationship</h2><p>Submitting a consultation request does not create an engagement or professional relationship. Hajime services begin only after both parties accept a written proposal or agreement defining the scope, fees, exclusions, and responsibilities.</p></section><section><h2>Licensed work</h2><p>Regulated services are performed by appropriately licensed professionals under their own responsibilities and, where applicable, their own engagement terms. Hajime coordinates work but does not direct or replace independent professional judgment.</p></section><section><h2>Pricing and third-party costs</h2><p>Website package prices describe the current validation offer and may change before a proposal is accepted. Government fees and third-party professional, translation, office, banking, insurance, payroll, and operating costs are separate unless a written proposal expressly includes them.</p></section><section><h2>Accuracy and availability</h2><p>Rules, provider requirements, processing times, and government practices can change. Hajime aims to keep public information useful but does not warrant that every item is complete, current, or suitable for a particular situation.</p></section><section><h2>Questions</h2><p>Use the <Link href="/book-consultation">consultation page</Link> for questions about these terms. These operational terms require review by Japanese counsel before becoming final public terms.</p></section></div>;
}
